# Generated by Django 4.0.3 on 2022-04-07 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserved_Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.TimeField()),
                ('date', models.DateField()),
                ('langauge', models.CharField(max_length=100)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movies')),
                ('theater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.theaters')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField(default=0)),
                ('seat_reserved_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='show.reserved_seat')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.shows')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('theater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.theaters')),
            ],
        ),
        migrations.AddField(
            model_name='reserved_seat',
            name='seat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.seats'),
        ),
        migrations.AddField(
            model_name='reserved_seat',
            name='show_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.shows'),
        ),
    ]
