# Generated by Django 4.0.2 on 2022-04-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seats',
            options={'verbose_name_plural': 'Seats'},
        ),
        migrations.AlterModelOptions(
            name='shows',
            options={'verbose_name_plural': 'Shows'},
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='tickets',
            name='seat_reserved_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.reserved_seat'),
        ),
    ]
