# Generated by Django 4.0.2 on 2022-04-24 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transection_code', models.CharField(max_length=400)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.tickets')),
            ],
        ),
    ]
