# Generated by Django 4.0.2 on 2022-04-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_bookedtickets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedtickets',
            options={'verbose_name_plural': 'Booked Tickets'},
        ),
        migrations.CreateModel(
            name='ReservedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.tickets')),
            ],
        ),
    ]
