# Generated by Django 4.0.2 on 2022-04-24 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('show', '0003_alter_bookedtickets_options_reservedticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservedticket',
            name='ticket_id',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='seat_reserved_id',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='user_id',
        ),
        migrations.AddField(
            model_name='reserved_seat',
            name='ticket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='show.tickets'),
        ),
        migrations.AlterField(
            model_name='reserved_seat',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BookedTickets',
        ),
        migrations.DeleteModel(
            name='ReservedTicket',
        ),
    ]
