# Generated by Django 4.0.2 on 2022-04-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_remove_reservedticket_ticket_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transection_code', models.CharField(max_length=400)),
                ('reserved_seat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='show.reserved_seat')),
                ('ticket_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='show.tickets')),
            ],
        ),
    ]
