# Generated by Django 4.0.2 on 2022-06-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_seats_ishousefull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='isHouseFull',
        ),
        migrations.AddField(
            model_name='shows',
            name='isHouseFull',
            field=models.BooleanField(default=False),
        ),
    ]
