# Generated by Django 4.0.2 on 2022-06-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_remove_seats_ishousefull_shows_ishousefull'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesWatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('show_id', models.CharField(max_length=10)),
                ('show_time', models.TimeField()),
                ('date', models.DateField()),
                ('theater_name', models.CharField(max_length=100)),
            ],
        ),
    ]
