# Generated by Django 4.0.2 on 2022-06-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0009_movieswatched'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieswatched',
            name='cover_image',
            field=models.ImageField(default=1, upload_to='images/movies_watched'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movieswatched',
            name='movie_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movieswatched',
            name='show_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='movieswatched',
            name='theater_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
