# Generated by Django 4.0.2 on 2022-06-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0010_movieswatched_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieswatched',
            name='id',
        ),
        migrations.AlterField(
            model_name='movieswatched',
            name='movie_name',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
