# Generated by Django 4.0.2 on 2022-06-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0012_alter_movieswatched_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieswatched',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movieswatched',
            name='movie_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
