# Generated by Django 4.0.2 on 2022-06-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0013_movieswatched_id_alter_movieswatched_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieswatched',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movieswatched',
            name='row',
            field=models.IntegerField(default=0),
        ),
    ]
