# Generated by Django 4.0.2 on 2022-06-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0014_movieswatched_number_movieswatched_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieswatched',
            name='movie_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
