# Generated by Django 4.0.2 on 2022-06-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0015_alter_movieswatched_movie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieswatched',
            name='id',
        ),
        migrations.AlterField(
            model_name='movieswatched',
            name='movie_name',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
