# Generated by Django 4.0.2 on 2022-06-08 02:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0016_remove_movieswatched_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieswatched',
            name='movie_name',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
