# Generated by Django 4.0.3 on 2022-04-07 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='images')),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please Enter the number in 9999999999 format.', regex='^\\??d{9,10}')])),
                ('country', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('total_seats', models.IntegerField(default=0)),
            ],
        ),
    ]
