# Generated by Django 4.0.2 on 2022-04-17 07:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='images')),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please Enter the number in 9999999999 format.', regex='^\\??\\d{9,10}$')])),
                ('country', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('total_seats', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Theaters',
            },
        ),
        migrations.CreateModel(
            name='TheaterReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('theater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.theaters')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Theater Reviews',
            },
        ),
    ]
