# Generated by Django 4.0.2 on 2022-04-09 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theaters',
            options={'verbose_name_plural': 'Theaters'},
        ),
        migrations.AlterField(
            model_name='theaters',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please Enter the number in 9999999999 format.', regex='^\\??\\d{9,10}$')]),
        ),
    ]
