# Generated by Django 4.0.2 on 2022-04-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_theaterreviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theaterreviews',
            options={'verbose_name_plural': 'Theater Reviews'},
        ),
    ]
