# Generated by Django 4.0.2 on 2022-06-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default=1, upload_to='images/profile_image'),
            preserve_default=False,
        ),
    ]
