# Generated by Django 4.0.2 on 2022-04-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium_user',
            field=models.BooleanField(default=False),
        ),
    ]
