# Generated by Django 4.0.3 on 2022-04-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(blank=True, max_length=100, verbose_name='movie name')),
                ('cover_image', models.ImageField(upload_to='images', verbose_name='cover image')),
                ('release_date', models.DateField(verbose_name='release date')),
                ('genres', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=150)),
                ('producers', models.CharField(blank=True, max_length=100)),
                ('descripton', models.TextField()),
                ('is_upcoming', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Movies',
            },
        ),
    ]
