# Generated by Django 4.0.2 on 2022-04-17 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(blank=True, max_length=100, verbose_name='movie name')),
                ('cover_image', models.ImageField(upload_to='images', verbose_name='cover image')),
                ('release_date', models.DateField(verbose_name='release date')),
                ('genres', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=150)),
                ('producers', models.CharField(blank=True, max_length=100)),
                ('casts', models.CharField(default='Not Defined', max_length=100)),
                ('descripton', models.TextField()),
                ('is_upcoming', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('user_id', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='premium_user')),
            ],
            options={
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
