# Generated by Django 4.0.2 on 2022-04-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movies_casts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name_plural': 'Movies'},
        ),
    ]
