# Generated by Django 4.0.2 on 2022-04-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movies_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
