# Generated by Django 4.0.2 on 2022-04-16 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0004_movies_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
